# Generated by Django 4.2.1 on 2023-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=30, verbose_name="Nombre"),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=40, verbose_name="Direccion"
                    ),
                ),
                (
                    "cell_phone",
                    models.CharField(default="", max_length=15, verbose_name="Celular"),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, null=True, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubes",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="", max_length=30, verbose_name="Razon_Social"
                    ),
                ),
                (
                    "legal_nature",
                    models.CharField(
                        default="", max_length=30, verbose_name="Naturaleza_juridica"
                    ),
                ),
                (
                    "nit",
                    models.CharField(default="", max_length=11, verbose_name="NIT"),
                ),
                (
                    "legal_representative_name",
                    models.CharField(
                        default="",
                        max_length=60,
                        verbose_name="Nombre_Representante_Legal",
                    ),
                ),
                (
                    "doc_type_legal_representative",
                    models.CharField(
                        choices=[
                            ("cedula_ciudadania", "CC"),
                            ("cedula_extranjeria", "CE"),
                            ("pasaporte", "PP"),
                            ("tarjeta_identidad", "TI"),
                            ("registro_civil", "RC"),
                        ],
                        default="cedula_ciudadania",
                        max_length=20,
                        verbose_name="Tipo_Doc_Representante_Legal",
                    ),
                ),
                (
                    "legal_representative_doc_number",
                    models.CharField(
                        default="",
                        max_length=15,
                        verbose_name="Num_Doc_Representante_Legal",
                    ),
                ),
                (
                    "cell_phone_legal_representative",
                    models.CharField(
                        default="",
                        max_length=15,
                        verbose_name="Celular_Representante_Legal",
                    ),
                ),
                (
                    "legal_representative_email",
                    models.EmailField(
                        max_length=60,
                        null=True,
                        verbose_name="Email_Representante_Legal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
    ]
