# Generated by Django 4.2.1 on 2023-05-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("miembros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="miembros.person",
            ),
        ),
    ]
