# Generated by Django 4.2.1 on 2023-06-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("miembros", "0008_student_attendant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="attendant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="miembros.attendant",
                verbose_name="Acudiente",
            ),
        ),
    ]
