# Generated by Django 4.2.1 on 2023-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.IntegerField(verbose_name="Numero_recibo")),
                (
                    "pay_day",
                    models.DateTimeField(default="", verbose_name="Fecha_Pago"),
                ),
                (
                    "value_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Valor_Pagado",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="", max_length=20, verbose_name="Metodo_Pago"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.CreateModel(
            name="ProductService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=40, verbose_name="Nombre"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Precio",
                    ),
                ),
                ("year", models.DateTimeField(verbose_name="Año")),
                (
                    "description",
                    models.CharField(
                        default="", max_length=1000, verbose_name="Descripcion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto_Servicio",
                "verbose_name_plural": "Productos_Servicios",
            },
        ),
    ]
